### ISSUE TITLE
[Informative] Differences

### ISSUE THREAD

**Issue by marcjal** [axetroy/dvm#23]
Hi 👋,

I would like to know the difference of this repository and this [dvm](https://github.com/justjavac/dvm), I'm trying to see which is more active with the community.

I so that this is project has interesting features that the other hasn't.

Thanks

**Comment by axetroy** [comment]
Hi!

When I developed this repository, it was because I was not satisfied with the version of [justjavac/dvm](https://github.com/justjavac/dvm). And at that time, it had not been maintained for a long time and in the "unavailable" state

So I decided to develop one myself.

Another reason is that I don’t like having node.js dependencies. this is what I describe in the project "without runtime dependencies"

Diff:
I haven't paid attention to its changes in a long time, just choose what you like

**Comment by marcjal** [comment]
Thanks @axetroy 

I'm going to start using this because has some features that are useful and also for what I saw this project it's update more frequently.

👋
